#!/bin/bash
#----------- Entregable EJ7 G10 -------------#
# Autores:                                   #
#   - Moreyra Iñigo, Juan Martin             #
#   - Piccinini, Luca                        #
#   - Taboada, Rodney                        #
#                                            #
# Descripcion:                               #
#   Programa correspondiente al entregable   # 
# del TP1 de SOYR                            #
#                                            #
#--------------------------------------------#
dir=$HOME/$1
file=$HOME/$2

if [ $# -ne 2 ];
then
    echo Numero de argumentos erroneos
elif [[ $1 =~ [./] || $2 =~ [./] ]];
then
    echo Caracteres no permitidos
elif [ -d $dir ];
then
    echo El directorio no se puede crear ya que este ya existe!
elif [ -f $file ];
then
    echo El archivo ya existe en $HOME
else
       
    mkdir $dir

    find /etc/ -maxdepth 1 -name "*.conf" -perm -o=r -exec cp -a {} $dir \;

    chmod go-rwx $dir/??g*
    
    ls -l $dir | tail -n +2 | sort -n -k 5 | head -n 5 > $file
    ls -l $dir | tail -n +2 | sort -f -r -k 9 | tail -n 5 >> $file 
   
fi

